language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"
install:
  - pip install -r requirements.txt -r tests/requirements.txt
cache: pip
script:
  - python3 -m pytest
branches:
  only:
  - dev
  - master
